
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;
using Cysharp.Threading.Tasks;

namespace cfg
{
public partial class Tables
{
    public zs.TbBuild TbBuild {get; private set; }
    public zs.TbBuildingLevel TbBuildingLevel {get; private set; }
    public zs.TbItem TbItem {get; private set; }
    public zs.TbGameConfig TbGameConfig {get; private set; }
    public zs.TbIsland TbIsland {get; private set; }
    public zs.TbIslandLevel TbIslandLevel {get; private set; }
    public zs.TbBuildingUnlock TbBuildingUnlock {get; private set; }
    public zs.TbGuideStep TbGuideStep {get; private set; }
    public zs.TbBridgeConfig TbBridgeConfig {get; private set; }

    /// public Tables(System.Func<string, ByteBuf> loader)
    public Tables()
    {
        ///        /// TbBuild = new zs.TbBuild(loader("zs_tbbuild"));
        ///        /// TbBuildingLevel = new zs.TbBuildingLevel(loader("zs_tbbuildinglevel"));
        ///        /// TbItem = new zs.TbItem(loader("zs_tbitem"));
        ///        /// TbGameConfig = new zs.TbGameConfig(loader("zs_tbgameconfig"));
        ///        /// TbIsland = new zs.TbIsland(loader("zs_tbisland"));
        ///        /// TbIslandLevel = new zs.TbIslandLevel(loader("zs_tbislandlevel"));
        ///        /// TbBuildingUnlock = new zs.TbBuildingUnlock(loader("zs_tbbuildingunlock"));
        ///        /// TbGuideStep = new zs.TbGuideStep(loader("zs_tbguidestep"));
        ///        /// TbBridgeConfig = new zs.TbBridgeConfig(loader("zs_tbbridgeconfig"));
        ///        /// ResolveRef();
    }

    public async UniTask LoadAsync(System.Func<string, UniTask<ByteBuf>> loader)
    {
        var tables = new System.Collections.Generic.Dictionary<string, object>();
		List<UniTask> list = new List<UniTask>();
		list.Add(UniTask.Create(async () =>
		{
			TbBuild = new zs.TbBuild(await loader("zs_tbbuild")); 
			tables.Add("zs.TbBuild", TbBuild);
		}));
		list.Add(UniTask.Create(async () =>
		{
			TbBuildingLevel = new zs.TbBuildingLevel(await loader("zs_tbbuildinglevel")); 
			tables.Add("zs.TbBuildingLevel", TbBuildingLevel);
		}));
		list.Add(UniTask.Create(async () =>
		{
			TbItem = new zs.TbItem(await loader("zs_tbitem")); 
			tables.Add("zs.TbItem", TbItem);
		}));
		list.Add(UniTask.Create(async () =>
		{
			TbGameConfig = new zs.TbGameConfig(await loader("zs_tbgameconfig")); 
			tables.Add("zs.TbGameConfig", TbGameConfig);
		}));
		list.Add(UniTask.Create(async () =>
		{
			TbIsland = new zs.TbIsland(await loader("zs_tbisland")); 
			tables.Add("zs.TbIsland", TbIsland);
		}));
		list.Add(UniTask.Create(async () =>
		{
			TbIslandLevel = new zs.TbIslandLevel(await loader("zs_tbislandlevel")); 
			tables.Add("zs.TbIslandLevel", TbIslandLevel);
		}));
		list.Add(UniTask.Create(async () =>
		{
			TbBuildingUnlock = new zs.TbBuildingUnlock(await loader("zs_tbbuildingunlock")); 
			tables.Add("zs.TbBuildingUnlock", TbBuildingUnlock);
		}));
		list.Add(UniTask.Create(async () =>
		{
			TbGuideStep = new zs.TbGuideStep(await loader("zs_tbguidestep")); 
			tables.Add("zs.TbGuideStep", TbGuideStep);
		}));
		list.Add(UniTask.Create(async () =>
		{
			TbBridgeConfig = new zs.TbBridgeConfig(await loader("zs_tbbridgeconfig")); 
			tables.Add("zs.TbBridgeConfig", TbBridgeConfig);
		}));

		await UniTask.WhenAll(list);

        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbBuild.ResolveRef(this);
        TbBuildingLevel.ResolveRef(this);
        TbItem.ResolveRef(this);
        TbGameConfig.ResolveRef(this);
        TbIsland.ResolveRef(this);
        TbIslandLevel.ResolveRef(this);
        TbBuildingUnlock.ResolveRef(this);
        TbGuideStep.ResolveRef(this);
        TbBridgeConfig.ResolveRef(this);
    }
}

}
