
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.zsEnum
{ 
    public enum TalentType
    {
        /// <summary>
        /// 提升生产/服务速率
        /// </summary>
        EfficiencyRate = 1,
        /// <summary>
        /// 提升产出物数量
        /// </summary>
        OutputRate = 2,
        /// <summary>
        /// 提升建筑储量上限
        /// </summary>
        StorageCapRate = 3,
    }

} 

