
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.zsEnum
{ 
    public enum PreferenceTag
    {
        /// <summary>
        /// 无
        /// </summary>
        Empty = 0,
        /// <summary>
        /// 美食
        /// </summary>
        Food = 1,
        /// <summary>
        /// 观景
        /// </summary>
        Sightseeing = 2,
        /// <summary>
        /// 冒险
        /// </summary>
        Adventure = 3,
        /// <summary>
        /// 休闲
        /// </summary>
        Leisure = 4,
        /// <summary>
        /// 娱乐
        /// </summary>
        Entertainment = 5,
        /// <summary>
        /// 社交
        /// </summary>
        Social = 6,
        /// <summary>
        /// 文化
        /// </summary>
        Culture = 7,
    }

} 

